### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by ghost** [ritamsaha00/dotfiles#2]
Thank you for using the theme that I made, by the way, are there no problems?  usually if used on gnome there must be something wrong...

**Comment by astro-ray** [comment]
There are many issues, but the one that happens most often is that pngs are not rendered properly. One way to solve that is to add the option `draw_blended = true`, but that makes it impossible to stack a png on top of another png even if the background is transparent.

**Comment by ghost** [comment]
ohh I see.. I'll note down maybe it could be a solution for others if there is an issue like this.

Regards
